name: continuous-integration

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

env:
  GO_VERSION: "~1.23"

jobs:
  ci-go-lint:
    name: ci-go-lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8

  ci-unit-tests:
    name: ci-unit-tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Run unit tests
      run:  go test ./...

  ci-build-example:
    name: ci-build-example
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Build example
      run:  go build -o mermaid-example ./example/main.go

    - name: Run example
      run: ./mermaid-example
